### ISSUE TITLE
Comparing SOM with other TSP algorithms

### ISSUE THREAD

**Issue by LucBerge** [DiegoVicen/som-tsp#10]
Hey there, thanks for the code @diego-vicente !

The SOM algorithm looks awesome but have you ever compared it with other algorithms ?
Is there a website comparing the TSP algorithms ?

**Comment by diego-vicente** [comment]
There is not much point to do so since the code is far from production-ready. Even if the very few cases where TSP could have a competitive advantage, this implementation would probably not be fair.

If you want more details regarding the performance, [there is a blog post](https://diego.codes/post/som-tsp/#implementing-and-testing-the-som) that compares the performance of this algorithm against the optimal solution for certain scenarios.

Closing this since there are no plans to include such benchmark.
