### ISSUE TITLE
A few comments needed

### ISSUE THREAD

**Issue by divlv** [DiegoVicen/som-tsp#6]
Hello Diego!
Can you please add some comments on TSP files.
I understand, that these are city coordinates.
OK, but why they are in such strange format - `25270.8333 51505.8333` ?
Why the generic format, e.g. `56.124122, 25.076389` is not used?

And why some coordinates are duplicated?
E.g. (assets/qa194.tsp file)
```
39 25270.8333 51505.8333
40 25270.8333 51523.0556
```
What's the point of duplicating `25270.8333` value? (and many others)

Also I've noticed, that many values has different integer part, but fraction parts of the values are the same:

3345 61200.0000 23466.**6667**
3346 61200.0000 23500.0000
3347 61200.0000 23766.**6667**
3348 61200.0000 24066.**6667**
3349 61200.0000 24100.0000

Why so?

**Comment by diego-vicente** [comment]
Hey Dmitrijs,

The TSPLIB files were downloaded from [a repository by the University of Waterloo](http://www.math.uwaterloo.ca/tsp/world/countries.html). In the full list it is possible to see that some of the countries have duplicated points, so you can select only the ones without them if this is getting in your way. In respect to the contents of the files, I'm afraid I cannot help much: I was also struck by the format, but it is probably related to the fact that regular latitude-longitude pairs may introduce some distortion if they are used to compute euclidean distances (this is just an intuition, I have no hard proof of it).

I know it's not much help, but I didn't really dig much further in how the data was collected and generated; I hope this is enough to at least give you a better lead on who to ask. I'm closing the issue because I don't know much about it, but feel absolutely free to keep on commenting in it if something is still unclear. Cheers!
