### ISSUE TITLE
Using SOM to find best bath in picking warehouse process

### ISSUE THREAD

**Issue by minels** [DiegoVicen/som-tsp#9]
Hi Diego,
I've just seen your work regarding self-organized map in salesman problem and I thank you for share your work.. I was looking some salesman problem solution because I'd like to implement something similar applied the process of peaces picking in my firm's warehouse.
Let me explain the issue: suppose there's a order of production included all peaces needed to accomplish that order.. naturally each peace is located in a different place of the warehouse... so it'll be usefull to find the best way.
I just need to change distance.py class due I'm not going to use euclidean metric... 
Am I right?

**Comment by diego-vicente** [comment]
Closing this issue since... Well it's not really an issue

Just to address your question really quick: yes, you're absolutely right, but bear in mind that for a reasonably sized warehouse and list of parts you should be looking into operational research and other optimal methods, since this is just an approximation
